# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ek8VGDutl6lPWSNyFH7b6dwStkGXn2Cs
"""

import pandas as pd
import numpy as np
import math
from sklearn.impute import SimpleImputer

data=pd.read_csv('train_final_hundred.csv')
columnnames=['id','month','n_seconds_1','n_seconds_2','n_seconds_3','carrier','devicebrand','feature_0','feature_1','feature_2','feature_3','feature_4','feature_5','feature_6','feature_7','feature_8','feature_9','feature_10','feature_11','feature_12','feature_13','feature_14','feature_15','feature_16','feature_17','feature_18','feature_19','feature_20','feature_21','feature_22','feature_23','feature_24','feature_25','feature_26','feature_27','feature_28','feature_29','feature_30','feature_31','feature_32','feature_33','feature_34','feature_35','feature_36','feature_37','feature_38','feature_39','feature_40','feature_41','feature_42','feature_43','feature_44','feature_45','feature_46','feature_47','feature_48','feature_49','menus']
data.columns=columnnames
#data.head()
# Yeni sütunları oluşturun

x = data.drop(columns=['menus','id','month','carrier','devicebrand','n_seconds_1','n_seconds_2','n_seconds_3','menus_1','menus_2','menus_3','menus_4','menus_5','menus_6','menus_7','menus_8','menus_9'])
y = data.menus_1.values.reshape(-1,)

print(x.shape)
print(y.shape)
#x=(xdata-np.min(xdata))/(np.max(xdata)-np.min(xdata))

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2,random_state=1)

import tensorflow as tf
model = tf.keras.models.Sequential()
print(x_train.shape)
print(y_train.shape)
model.add(tf.keras.layers.Dense(256, input_shape=(50,), activation=None))
model.add(tf.keras.layers.Dense(1, activation='sigmoid'))

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

print(y_train.shape)
print(x_train.shape)
model.fit(x_train, y_train, epochs=1000)



model.evaluate(x_test, y_test)